### PR TITLE
Bumb to chrome driver 102

### PR DESCRIPTION
**Pull request by Beltarm**

### CODE REVIEW

**Comment by kavilla** [comment]
Hello! Any ETA on this getting merged in? Thanks!

**Comment by asm95** [comment]
For yarn v2 users, while waiting for them to merge the 102:
```bash
yarn add "chromedriver@https://github.com/Beltarm/node-chromedriver#refs/heads/chromedriver-102"
```

To check, you can use the following command in the root of your project folder (where `package.json` file exists):

```bash
./node_modules/chromedriver/bin/chromedriver --version
# ChromeDriver 102.0.5005.61 (0e59bcc00cc4985ce39ad31c150065f159d95ad3-refs/branch-heads/5005@{#819})
```

In your package.json you'll find something like this:

```json
"dependencies": {
 "chromedriver": "https://github.com/Beltarm/node-chromedriver#refs/heads/chromedriver-102"
}
```

**Comment by ephill** [comment]
@giggio Any chance we can get this merged? It's a blocking issue for myself and probably many others.

**Comment by giggio** [comment]
I'll release it as soon as the build passes.

**Comment by giggio** [comment]
Thanks @Beltarm .

**Pull request merged**
