### PR TITLE
fix: support 30x redirect download for binaries url

### PR DESCRIPTION
**Pull request by fengmk2**
The custom download url maybe redirect to S3 or other cloud store url.

### CODE REVIEW

**Comment by giggio** [comment]
Can you get me an example to try?

**Comment by fengmk2** [comment]
Try this

```bash
CHROMEDRIVER_CDNURL=http://npm.taobao.org/mirrors/chromedriver node install.js
```

**Comment by fengmk2** [comment]
@giggio any suggestion?

**Comment by giggio** [comment]
@fengmk2 sorry about the delay. This would recurse indefinitely. Maybe we could add a limit?

**Comment by giggio** [comment]
Closing by inactivity. If you want to complete this, let me know.

**Comment by fengmk2** [comment]
Yep, I will send a new pr and add redirect limit.

**Pull request closed without merging**
