### PR TITLE
Update to chrome 92

### PR DESCRIPTION
**Pull request by TCashion**
This is a similar scenario to [pull request 310](https://github.com/giggio/node-chromedriver/pull/310) where https://chromedriver.storage.googleapis.com/LATEST_RELEASE shows version `91.0.*`, but version `92.0.4515.43` is available on https://chromedriver.chromium.org/downloads.

### CODE REVIEW

**Comment by giggio** [comment]
Thanks for the PR, but 92 is not stable yet. You can see it at their home page or at: https://chromedriver.storage.googleapis.com/LATEST_RELEASE
As soon as it is out, please let me know and I'll review it. PR looks fine so far.

**Comment by TCashion** [comment]
@giggio thank you for taking a look. I was able to update Chrome on my machine yesterday:
Screen Shot 2021-07-22 at 9 03 43 AM

**Comment by rsshilli** [comment]
> @giggio thank you for taking a look. I was able to update Chrome on my machine yesterday:
> Screen Shot 2021-07-22 at 9 03 43 AM

Me too! My Chrome browser automatically updated with any intervention from me. I think the latest release file is wrong.

**Comment by giggio** [comment]
It seems they are lagging behind. I just published it. Closes #321.

**Pull request merged**
