### PR TITLE
Bump Chromedriver to version 105.0.5195.19

### PR DESCRIPTION
**Pull request by JonWallsten**
Bump Chromedriver to version 105.0.5195.19
Bump package version to 105.0.0

### CODE REVIEW

**Comment by giggio** [comment]
Hello, 105 is still beta, when it is published to stable ping me back here so we can review it.
See it at: https://chromedriver.chromium.org/

**Comment by JonWallsten** [comment]
Oh, sorry. I went straight to the downloads page where it doesn't say it's a beta version. So totally missed that.

**Comment by jmdecide** [comment]
@giggio Hey! chrome 105 is live, can we have this merged? :)

**Comment by giggio** [comment]
Closed in favor of #377.

**Pull request closed without merging**
