### PR TITLE
Bump chromedriver to 75.0.3770.8

### PR DESCRIPTION
**Pull request by jazzzz**

### CODE REVIEW

**Comment by jazzzz** [comment]
> It is still beta...

You're right. My issue is that I use it with the [chromium npm package](https://www.npmjs.com/package/chromium) that uses a version of Chromium that is compatible only with Chromedriver 75. Would it be possible to publish a beta version of chromedriver? (I would change the package version to reflect it).

**Comment by giggio** [comment]
Wouldn't the versioning scheme we have help? https://github.com/giggio/node-chromedriver#versioning
You could set an env var and it would pick it up.

**Comment by jazzzz** [comment]
It totally helps! Thanks!

**Comment by Merter** [comment]
It is stable now and I have created another PR for it.

**Pull request closed without merging**
