### PR TITLE
Update to 2.22

### PR DESCRIPTION
**Pull request by ex1st**

### CODE REVIEW

**Comment by dcypherthis** [comment]
👍 due to issues with chrome 50/51

**Comment by serenanubi** [comment]
Can someone merge this please :)? Our team could really use it

**Comment by sfbwalder** [comment]
@giggio We would also appreciate a merge and a new version published to npm.

**Comment by rkavalap** [comment]
This is temporary fix. Ideally the fix should be to read LATEST_RELEASE file under chromedriver.storage.googleapis.com and use the version

**Comment by mattSleeman** [comment]
@giggio Do we know when the merge is likely to happen?

**Comment by giggio** [comment]
PR merged and pushed to npm. Sorry for the delay, everyone, I have been busy.
@rkavalap We need to publish exact versions to NPM, otherwise you would get a newer version even if you do not want it. Maybe we could add this as an option?

**Comment by rkavalap** [comment]
@giggio Agreed, adding the version information information as on option would be ideal.

**Comment by sfbwalder** [comment]
@giggio  Thanks for merging and publishing!!!

**Pull request merged**
