### PR TITLE
Update CromeDriver to version 88

### PR DESCRIPTION
**Pull request by xmtigra**

### CODE REVIEW

**Comment by longxia0324** [comment]
chrome driver current version： 88.0.4324.96

**Comment by ravichillerega** [comment]
Waiting for this version to be available.

**Comment by smart-apeha** [comment]
And what are you still waiting?

**Comment by smart-apeha** [comment]
Чего ждем то??? Второго пришествия?

**Comment by giggio** [comment]
I just published version 88. This PR had an issue with the package-lock.json, so I thought it was easier to just run `update.js` and publish.
Thanks anyway.

**Pull request closed without merging**
