### PR TITLE
Added shippable.yml file to test builds in aarch64 platform

### PR DESCRIPTION
**Pull request by ossdev07**
Added shippable.yml file to test the builds in aarch64 platform. 

To start building in shippable in x86 platform, please go through below link for the same:
http://docs.shippable.com/getting-started/ci-sample/

To build projects in arm platform, please go to below link for the same:
http://docs.shippable.com/platform/tutorial/workflow/run-ci-builds-on-arm/

Please revert if any more queries on shippable.
Thanks in advance.

### CODE REVIEW

**Comment by giggio** [comment]
@ossdev07 I created the build on Shippable, but I am getting an error:

```
Job skippedInfoInfoLicense to run this job on node pool "shippable_shared_aarch64" not found. Ask a Shippable adminstrator to assign the appropriate license.
```

Here is the build result, you can see this message in the logs that you download:

https://app.shippable.com/github/giggio/node-chromedriver/runs/4/1/console

I have created the branch `shippable` to test it. How do I solve this?

**Comment by ossdev07** [comment]
@giggio Require license to run arm builds. Please go through below link to raise a ticket for license in shippable:
http://docs.shippable.com/platform/tutorial/workflow/run-ci-builds-on-arm/

Please revert if any issues facing to raise a ticket for license.

**Comment by giggio** [comment]
Ok, I just requested the license. As soon as it is done I'll check back.

**Comment by giggio** [comment]
Code integrated directly. Thanks @ossdev07 !

**Comment by pruthvireddy1991** [comment]
Thanks for accepting the pull request. Please update the receipent mail id to generic mail in shippable.yml.
Thanks in advance.

**Comment by giggio** [comment]
@ossdev07 sure, done!

**Comment by ossdev07** [comment]
@giggio Thanks.

**Pull request closed without merging**
