### PR TITLE
enable downloads over https (instead of http only).

### PR DESCRIPTION
**Pull request by heijmans**

### CODE REVIEW

**Comment by Jessevanbekkum** [comment]
Very good idea. I like using only https for downloading software on my build server.

**Comment by RRMoelker** [comment]
Sounds great and fixes #48. Who can merge this PR? @giggio ?

**Comment by sfbwalder** [comment]
@giggio We would also appreciate a merge and a new version published to npm.

**Comment by sfbwalder** [comment]
@heijmans Thanks for creating this fork/pull that allows https.  We need another feature, which is having the options.rejectUnauthorized follow the strict-ssl npm config property.  I made a local copy and published it to our internal npm registry so it would work for us.  If you feel this will work for you also here are the few changes you could add:

```javascript
 return requestBinary(getRequestOptions(conf), downloadedFile)  //pass entire conf to setup options

function getRequestOptions(npmConf) {  // receive entire conf
  var options,
	proxyUrl = npmConf.get('proxy')  //pull out proxy so existing code will work

 options.rejectUnauthorized = npmConf.get('strict-ssl');  //set to whatever strict-ssl is set to (default=true)
```
Again, that is changes only, with many lines of code left out.

I would have opened an issue on your fork, but looks like I couldn't.  

Hopefully this will all get merged soon.

**Comment by giggio** [comment]
Sorry for the delay. Published as version `2.22.1`.

**Comment by sfbwalder** [comment]
@giggio Thanks for merging and publishing!!!

**Pull request merged**
