### PR TITLE
replace axios \w built in fetch

### PR DESCRIPTION
**Pull request by jimmywarting**

### CODE REVIEW

**Comment by giggio** [comment]
@jimmywarting the build is not passing, you removed axios from `update.js` but not from `install.js`.

**Review by giggio — CHANGES_REQUESTED** [review]
@jimmywarting the build is not passing, you removed axios from `update.js` but not from `install.js`.

**Comment by jimmywarting** [comment]
oh, so it did require more stuff...

**Comment by giggio** [comment]
Yes, and we can't do it while we support Node 14 and 16.

**Pull request closed without merging**
