### PR TITLE
Replace node http module with request

### PR DESCRIPTION
**Pull request by alexdavid**
node-chromedriver was not respecting the `NO_PROXY` environment variable. By using [Mikeal's request module](https://github.com/request/request) we get support for proxies as well as `NO_PROXY` for free.

### CODE REVIEW

**Comment by alexdavid** [comment]
@giggio Could you review this when you get a chance please?

Thanks!

**Comment by giggio** [comment]
@alexdavid I am on vacation right now... When I get back I will take a look at this. I am already working more than I should during vacation time. :)

**Comment by alexdavid** [comment]
Sure thing, thanks!

Enjoy your vacation :)

**Comment by charlierudolph** [comment]
@giggio bump on this (if you're back from vacation)

**Comment by giggio** [comment]
Published as 2.15.1: https://www.npmjs.com/package/chromedriver
Sorry it took me so long, I am usually faster than this.

**Pull request merged**
