### PR TITLE
Add support for downloading the chromedriver after installation

### PR DESCRIPTION
**Pull request by r3pwn**
Using the `.download` async function, we can now do things like 

`await chromedriver.download();`
before any tests get run. 

Additionally, some options are supported. 
We can pass in `download_version` or `cdn_url` like such:
`await chromedriver.download({cdn_url: "http://localhost", download_version: 84});`

`download_version` is able to be passed in as the full version of chrome (`"84.0.4147.105"`) or just the major version (`84`)

I believe this is the functionality requested by @HaimBendanan in issue #256

### CODE REVIEW

**Comment by r3pwn** [comment]
The only additional thing that I think may be beneficial to have as a part of this is an exported `is_installed` function on `lib/chromedriver.js` which will allow whoever is using it to see if they need to download chromedriver, or if it's set up properly already, but I will wait for feedback.

**Comment by giggio** [comment]
Wow, this is a large PR, I'll check it out on the weekend.

**Comment by r3pwn** [comment]
I tested this code using a sample project and adding the following snippet, and it seems to work as intended. Please let me know if you have any questions :)

image

**Comment by r3pwn** [comment]
@giggio Have you had the chance to look at this PR?

**Comment by r3pwn** [comment]
@giggio Did you ever get a chance to look at this?

**Comment by bhuber2010** [comment]
would love to get this merged as well!

**Comment by dboterho** [comment]
+1

**Pull request closed without merging**
