### PR TITLE
Update to latest version 93

### PR DESCRIPTION
**Pull request by ZackDeRose**
Hope I did this right!

### CODE REVIEW

**Comment by giggio** [comment]
@ZackDeRose it is correct, but 93 is not stable yet, so I'll wait until it is released, ok?

**Comment by moming2k** [comment]
stable Chrome released version 93, would this pull request get merged and publish to npm ? Many Thanks.

**Comment by moming2k** [comment]
The version in my Mac machine show 93.0.4577.63 , I am not sure if other system would have the same version number ?

The source code that included in this pull request is using 93.0.4577.15.

**Comment by RajaBellebon** [comment]
Hey,

thank you so much for this package!

We would like to use it for chrome 93 that has been recently released.

* @ZackDeRose are you going to fix the conflicts?

* @giggio that would be awesome to have this version released soon

Regards,

**Comment by tmadison-gpsw** [comment]
Related #326

**Comment by giggio** [comment]
Sorry, the pr had conflicts, I updated directly. It is on npm now.

**Comment by RajaBellebon** [comment]
Thank you!

**Pull request closed without merging**
