### PR TITLE
add an option `includeChromium` to include Chromium while checking for Chrome's version

### PR DESCRIPTION
**Pull request by ccheraa**
This will make use of the changes in this PR testimio/chrome-version#9 to check for Chromium also and not only Chrome, and will not have any effect on the current version of `chrome-version` which is `1.0.7`

### CODE REVIEW

**Comment by yamahito** [comment]
Resolves #335

**Comment by ccheraa** [comment]
(to prevent stale-bot from closing this)

**Comment by adamretter** [comment]
@ccheraa Do we also need to update the version of `chrome-version`? like in this PR - https://github.com/giggio/node-chromedriver/pull/346

**Comment by adamretter** [comment]
Hi there @giggio I wondered if you might consider merging this PR and creating a new release to npm.js?

**Comment by giggio** [comment]
Ok, this looks good. I had recently updated to the latest version of `chrome-version`, so that should be done already. I'm only missing the docs on the readme explaining the new flag, please add that, fix the small conflict, and we can merge.

**Comment by ccheraa** [comment]
@giggio I have updated `README.md`, please check again.

**Comment by giggio** [comment]
@ccheraa that looks good. Would you please remove the changes to `package-lock.json` and `package.json` files?

**Comment by adamretter** [comment]
@giggio Are you happy with this now?

**Comment by giggio** [comment]
Thanks @ccheraa! I just published it to npm as chromedriver@97.0.3.

**Pull request merged**
