### PR TITLE
 Chromedriver 2.34 and version bump to 2.34.0

### PR DESCRIPTION
**Pull request by mdbarr**
Chromedriver 2.34 and version bump to 2.34.0

### CODE REVIEW

**Comment by simplyageek** [comment]
Could we review & merge this, pls?

**Comment by fzaninotto** [comment]
Bump, this is blocking as the latest Chrome isn't supported by the current driver.

**Comment by giggio** [comment]
Released to npm just now. Thanks everyone.

**Comment by fzaninotto** [comment]
Thank you very much!

**Pull request merged**
