### PR TITLE
Add chromedriver path to PATH environment variable

### PR DESCRIPTION
**Pull request by mucsi96**

### CODE REVIEW

**Comment by mucsi96** [comment]
According to node.js documentation. We can write to process.env object, and changes won't be reflected outside of the process. 
With this change using chromedriver with selenium-webdriver will be much more easy. 
So instead of this: 

```javascript
var webdriver = require('selenium-webdriver');
var chrome = require('selenium-webdriver/chrome');
var path = require('chromedriver').path;

var service = new chrome.ServiceBuilder(path).build();
chrome.setDefaultService(service);

var driver = new webdriver.Builder()
    .withCapabilities(webdriver.Capabilities.chrome())
    .build();
```

we can do this:
```javascript
require('chromedriver');
var path = require('path'),
    driver = new require('selenium-webdriver').Builder()
        .withCapabilities(webdriver.Capabilities.chrome())
        .build();
```

**Comment by MetaMemoryT** [comment]
:+1: ooo

**Comment by giggio** [comment]
Merged. I can see you are a windows guy. :)
I had to change from `;` to `path.delimiter`. See 810490d for more details.
Published as `2.21.2`.

**Comment by mucsi96** [comment]
Thanks. It was a long time ago. Now I am a Mac guy :)

**Pull request merged**
