### PR TITLE
Updating to support Chromedriver 2.25

### PR DESCRIPTION
**Pull request by vasikarla**
@giggio : kindly review

### CODE REVIEW

**Comment by davscro** [comment]
Thanks for pull request, I'm also waiting for it.

**Comment by rkavalap** [comment]
@vasikarla i think the version in package.json should be 2.25.0

**Comment by vasikarla** [comment]
@rkavalap : done.

**Comment by vasikarla** [comment]
@giggio : please fix this when you get a chance

**Comment by vasikarla** [comment]
@giggio : could you kindly merge this as this is blocking lot of our tests.  appreciate your help in advance.

**Comment by giggio** [comment]
Also published to the npm registry.

**Comment by vasikarla** [comment]
Thanks @giggio

**Pull request merged**
