### PR TITLE
Use request library to perform download

### PR DESCRIPTION
**Pull request by Toilal**
It should fix all issues users have to download the binary through proxies.

requests supports the common `http_proxy` and `https_proxy` environment variables so it's not usefull to add them in this module. And it can be easily configured with [proxy option](https://github.com/request/request#proxies), that's what i've done for the npm config proxy settings.

It just works without any hack for `http => http` and `http => https` tunneling.

### CODE REVIEW

**Comment by giggio** [comment]
I am willing to consider it the PR, I did not want to use request because it brings 50+ extra packages. But I checked, and it is only about 6 MBs. I can't do it right now, but I will check it later. I need to get a proxy up and test everything.

**Comment by Toilal** [comment]
You can also check #97 : it implements a solution without additional dependency, but it fallbacks to http instead of https in some case. 

Maybe one day chromedriver won't be served on http anymore, and it seems much more like a hack that this one.

**Comment by Shingaz** [comment]
I am waiting for this PR too. It fixes #78 #80 #85 #91 and others probably.

**Comment by yannbertrand** [comment]
Please go for it :smile:

**Comment by giggio** [comment]
Published to NPM as version 2.29.1.
Sorry it took me so long, I just had entered on vacation when this PR came in.

**Pull request merged**
