### PR TITLE
update default driver version to 85.x, bump module to 85.0.0

### PR DESCRIPTION
**Pull request by dmlemeshko**
Updating default driver to match recently released Chrome 85

### CODE REVIEW

**Comment by dmlemeshko** [comment]
@giggio could you review it?

**Comment by gesaho** [comment]
when it is going to be merged and available to download? We are facing issue as chrome browser is 85 and the driver is yet at 84. so we are facing failures.

**Comment by msessom** [comment]
+1

**Comment by giggio** [comment]
Merged and published. Thanks.

**Pull request merged**
