### PR TITLE
fix: support 30x redirect download for binaries url

### PR DESCRIPTION
**Pull request by fengmk2**
The custom download url maybe redirect to S3 or other cloud store url.

### CODE REVIEW

**Comment by fengmk2** [comment]
ping @giggio

**Comment by giggio** [comment]
I get the changes on `travis.yml` but it is not clear the other change. I never got 30x redirects that I remember. And why the new dependency?

**Comment by fengmk2** [comment]
Our mirror site will redirect to aliyun oss store.

```bash
curl -v 'http://npm.taobao.org/mirrors/chromedriver/2.19/chromedriver_mac32.zip'
*   Trying 42.120.63.172...
* Connected to npm.taobao.org (42.120.63.172) port 80 (#0)
> GET /mirrors/chromedriver/2.19/chromedriver_mac32.zip HTTP/1.1
> Host: npm.taobao.org
> User-Agent: curl/7.43.0
> Accept: */*
> 
< HTTP/1.1 302 Found
< Server: nginx/1.1.19
< Date: Wed, 30 Sep 2015 04:46:57 GMT
< Content-Type: text/html; charset=utf-8
< Content-Length: 173
< Connection: keep-alive
< Vary: Accept-Encoding
< Location: http://oss.npm.taobao.org/dist/chromedriver/2.19/chromedriver_mac32.zip
< X-Response-Time: 3
< 
* Connection #0 to host npm.taobao.org left intact
Redirecting to <a href="http://oss.npm.taobao.org/dist/chromedriver/2.19/chromedriver_mac32.zip">http://oss.npm.taobao.org/dist/chromedriver/2.19/chromedriver_mac32.zip</a>.
```

**Comment by fengmk2** [comment]
@giggio Can this merge?

**Comment by giggio** [comment]
I don't really like the idea of bringing in so many dependencies.
Also, you state on [urllib](https://github.com/node-modules/urllib):

> Otherwise, this library will crash the process and exit, so you might as well install bluebird as a dependency!

I don't want to have to deal with that.

If you can find a way to solve the problem without adding an extra library which also assumes other dependencies are installed, I'll look into it

**Comment by fengmk2** [comment]
OK.

**Comment by fengmk2** [comment]
@giggio Please take a view at #42

**Pull request closed without merging**
